version: '3.4'

services:
  clientservice:
    image: ${DOCKER_REGISTRY-}clientservice
    build:
      context: .
      dockerfile: src/ClientService/DockerfileDev
    depends_on:
      - authenticationservice

  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: src/AuthenticationService/Dockerfile