version: '3.4'

services:
  clientservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - angularfrontend
  angularfrontend:
    image: ${DOCKER_REGISTRY-}angularfrontend
    build:
      context: .
      dockerfile: src/ClientService/ClientApp/Dockerfile
    container_name: AngularFrontend
    ports:
      - "4200:4200"
    volumes:
      - "./src/ClientService/ClientApp:/app"
  authenticationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - env/AuthenticationService.env
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
